### ISSUE TITLE
Not compatible with 2.1.x anymore

### ISSUE THREAD

**Issue by GuidoHub** [tig-nl/postcode-magento2#10]
From update 1.1.11 you require magento/module-quote 101.0.5 or higher but magento 2.1.16 has 100.1.10

**Comment by tig-dennisvanderhammen** [comment]
Hi @GuidoHub,

We dropped the support of Magento 2.1 in version 1.1.11, that's why you're unable to retrieve any version higher than 1.1.10.

Because of the dropped support, we haven't tested version 1.1.10 for Magento 2.1.16, but I did change the framework limitations in this version to also allow version 2.1.16. If you do have v1.1.10 installed, the following command should change your current version.

composer require tig/postcode-magento2:1.1.10

Could you tell me if this is a working solution for you?

**Comment by tig-dennisvanderhammen** [comment]
Hi @GuidoHub,

I haven't received a reply from you, so I'm assuming you got the extension working. If this is not the case, feel free to reopen this issue or please send us an e-mail at support@tig.nl.
