### ISSUE TITLE
[BUG] Postcode validation not working properly customer address book

### ISSUE THREAD

**Issue by dehaan-jeroen** [tig-nl/postcode-magento2#33]
**To Reproduce**
1. Sign in to a customer account
2. Go to the customer address book
3. Change an address in the address book, or create a new address
4. Fill in the form with an invalid postcode. For example, enter 2 digits in the postcode field.

**Expected result**
An error should display, stating that the entered postcode is invalid. The button to submit the form should be disabled. The customer should not be able to send the form and change their address.

**Actual result**
A warning is displayed when leaving the postcode field. When submitting the form an error is displayed, but the form is still being sent and the customer has changed their account to an account with an invalid address.

**Workaround**
None

** Please complete the following information**
- Magento version: Magento 2.4.2
- PHP version: 7.3.28

**Comment by tig-jeffreybranderhorst** [comment]
hi @dehaan-jeroen ,

I will place this on the backlog to check on the format of postcodes. We did decide to let postcodes through if we don't know them, what means if a postcode is filled in correctly with 1234 xx but is not recognized we will let it through.  What I will put on the backlog is to check if the postcode is 1234 xx instead of only 1234 for the Netherlands in this example. 

Have a great day,
Jeffrey
