### ISSUE TITLE
Housenumber not set in Shipping address

### ISSUE THREAD

**Issue by kaushalsutharhs** [tig-nl/postcode-magento2#5]
Magento ver. 2.2.3
postcode-magento2 version:1.1.7

> vendor/tig/postcode-magento2/Plugin/Address/Management/Shipping.php

        $attributes = $address->getExtensionAttributes();

In Above line it's return NULL and Billing.php working fine.

So in Billing address it saving house number properly in Street and in Shipping it's not.. So what could be wrong?

**Comment by kaushalsutharhs** [comment]
Yes @tig-rikjonkmans still using onestepcheckout/iosc

**Comment by tig-rikjonkmans** [comment]
Hi @kaushalsutharhs, ok than thats the reason the house number is not parsed correctly. 
Making the extension compatible with iosc is on our backlog. I already did some research and this problem is caused because of the way iosc saves the shipping address during the checkout process.

Once the postcode extension is compatible i will let you know.

**Comment by kaushalsutharhs** [comment]
@tig-rikjonkmans Thanks :)

**Comment by tig-jaspersmits** [comment]
I'm closing this, because this should be solved.
