### ISSUE TITLE
[QUESTION] why is house number not a required field

### ISSUE THREAD

**Issue by Giovanni-Schroevers** [tig-nl/postcode-magento2#54]
**Question**
Hey, I was wondering why the house number field is not marked as a required field. The hidden magento field still gives an error and prevents the user from going to the next step of the checkout without any visible error messages, causing possible confusion. 

I assumed this was the intended behaviour given the fact that this is also looks to be the case for the examples in the readme.

**Comment by tig-jeffreybranderhorst** [comment]
Hi @Giovanni-Schroevers ,

We have not required our house number field because we hide it if other countries are selected. If we would require it this will mean that you cannot check out anymore with the other countries because it will expect the house number that is not visible, that is the reason we don't required it. Thank you for your question! 

Have a great day,
Jeffrey
